name: Frontend Check Build and Lint

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
